In [1]:
import pandas as pd

actor = pd.read_csv('movie_dataset/actor.csv')
address = pd.read_csv('movie_dataset/address.csv')
category = pd.read_csv('movie_dataset/category.csv')
city = pd.read_csv('movie_dataset/city.csv')
country = pd.read_csv('movie_dataset/country.csv')
customer = pd.read_csv('movie_dataset/customer.csv')
film = pd.read_csv('movie_dataset/film.csv')
film_actor = pd.read_csv('movie_dataset/film_actor.csv')
film_category = pd.read_csv('movie_dataset/film_category.csv')
inventory = pd.read_csv('movie_dataset/inventory.csv')
language = pd.read_csv('movie_dataset/language.csv')
payment = pd.read_csv('movie_dataset/payment.csv')
rental = pd.read_csv('movie_dataset/rental.csv')
staff = pd.read_csv('movie_dataset/staff.csv')
store = pd.read_csv('movie_dataset/store.csv')

In [2]:
def tag(x):
    if x > 8.99:
        return "High"
    elif x > 4.99:
        return "Medium"
    else:
        return "Low"

In [3]:
payment['category']=payment['amount'].apply(tag)

In [4]:
payment

,payment_id,customer_id,staff_id,rental_id,amount,payment_date,category
0,16050,269,2,7,1.99,2020-01-25 03:10:19.996577+05:30,Low
1,16051,269,1,98,0.99,2020-01-25 20:46:50.996577+05:30,Low
2,16052,269,2,678,6.99,2020-01-29 03:14:14.996577+05:30,Medium
3,16053,269,2,703,0.99,2020-01-29 06:28:02.996577+05:30,Low
4,16054,269,1,750,4.99,2020-01-29 13:40:06.996577+05:30,Low
...,...,...,...,...,...,...,...
16044,32094,245,2,12682,2.99,2020-05-14 18:14:29.996577+05:30,Low
16045,32095,251,1,14107,0.99,2020-05-14 18:14:29.996577+05:30,Low
16046,32096,252,2,13756,4.99,2020-05-14 18:14:29.996577+05:30,Low
16047,32097,263,1,15293,0.99,2020-05-14 18:14:29.996577+05:30,Low
16048,32098,264,2,14243,2.99,2020-05-14 18:14:29.996577+05:30,Low

In [5]:
payment.groupby('customer_id')['amount'].agg(['sum','count','max','min','mean'])

                sum  count    max   min      mean
customer_id
1            118.68     32   9.99  0.99  3.708750
2            128.73     27  10.99  0.99  4.767778
3            135.74     26  10.99  0.99  5.220769
4             81.78     22   8.99  0.99  3.717273
5            144.62     38   9.99  0.99  3.805789
...             ...    ...    ...   ...       ...
595          117.70     30  10.99  0.99  3.923333
596           96.72     28   6.99  0.99  3.454286
597           99.75     25   8.99  0.99  3.990000
598           83.78     22   7.99  0.99  3.808182
599           83.81     19   9.99  0.99  4.411053

[599 rows x 5 columns]

In [6]:
payment['amount2']=payment['amount']*3
payment

,payment_id,customer_id,staff_id,rental_id,amount,payment_date,category,amount2
0,16050,269,2,7,1.99,2020-01-25 03:10:19.996577+05:30,Low,5.97
1,16051,269,1,98,0.99,2020-01-25 20:46:50.996577+05:30,Low,2.97
2,16052,269,2,678,6.99,2020-01-29 03:14:14.996577+05:30,Medium,20.97
3,16053,269,2,703,0.99,2020-01-29 06:28:02.996577+05:30,Low,2.97
4,16054,269,1,750,4.99,2020-01-29 13:40:06.996577+05:30,Low,14.97
...,...,...,...,...,...,...,...,...
16044,32094,245,2,12682,2.99,2020-05-14 18:14:29.996577+05:30,Low,8.97
16045,32095,251,1,14107,0.99,2020-05-14 18:14:29.996577+05:30,Low,2.97
16046,32096,252,2,13756,4.99,2020-05-14 18:14:29.996577+05:30,Low,14.97
16047,32097,263,1,15293,0.99,2020-05-14 18:14:29.996577+05:30,Low,2.97
16048,32098,264,2,14243,2.99,2020-05-14 18:14:29.996577+05:30,Low,8.97

In [7]:
payment.groupby('customer_id')[['amount','amount2']].agg(['sum','count','max','min','mean'])

             amount                              amount2                     \
                sum count    max   min      mean     sum count    max   min
customer_id
1            118.68    32   9.99  0.99  3.708750  356.04    32  29.97  2.97
2            128.73    27  10.99  0.99  4.767778  386.19    27  32.97  2.97
3            135.74    26  10.99  0.99  5.220769  407.22    26  32.97  2.97
4             81.78    22   8.99  0.99  3.717273  245.34    22  26.97  2.97
5            144.62    38   9.99  0.99  3.805789  433.86    38  29.97  2.97
...             ...   ...    ...   ...       ...     ...   ...    ...   ...
595          117.70    30  10.99  0.99  3.923333  353.10    30  32.97  2.97
596           96.72    28   6.99  0.99  3.454286  290.16    28  20.97  2.97
597           99.75    25   8.99  0.99  3.990000  299.25    25  26.97  2.97
598           83.78    22   7.99  0.99  3.808182  251.34    22  23.97  2.97
599           83.81    19   9.99  0.99  4.411053  251.43    19  29.97  2.97


                  mean
customer_id
1            11.126250
2            14.303333
3            15.662308
4            11.151818
5            11.417368
...                ...
595          11.770000
596          10.362857
597          11.970000
598          11.424545
599          13.233158

[599 rows x 10 columns]

In [8]:
payment.groupby('customer_id').agg({'amount':['sum','count'],'amount2':'mean'})

             amount          amount2
                sum count       mean
customer_id
1            118.68    32  11.126250
2            128.73    27  14.303333
3            135.74    26  15.662308
4             81.78    22  11.151818
5            144.62    38  11.417368
...             ...   ...        ...
595          117.70    30  11.770000
596           96.72    28  10.362857
597           99.75    25  11.970000
598           83.78    22  11.424545
599           83.81    19  13.233158

[599 rows x 3 columns]

In [9]:
actor.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   actor_id     200 non-null    int64
 1   first_name   200 non-null    str
 2   last_name    200 non-null    str
 3   last_update  200 non-null    str
dtypes: int64(1), str(3)
memory usage: 6.4 KB

In [10]:
actor

     actor_id first_name     last_name                last_update
0           1   PENELOPE       GUINESS  2020-02-15 15:04:33+05:30
1           2       NICK      WAHLBERG  2020-02-15 15:04:33+05:30
2           3         ED         CHASE  2020-02-15 15:04:33+05:30
3           4   JENNIFER         DAVIS  2020-02-15 15:04:33+05:30
4           5     JOHNNY  LOLLOBRIGIDA  2020-02-15 15:04:33+05:30
..        ...        ...           ...                        ...
195       196       BELA        WALKEN  2020-02-15 15:04:33+05:30
196       197      REESE          WEST  2020-02-15 15:04:33+05:30
197       198       MARY        KEITEL  2020-02-15 15:04:33+05:30
198       199      JULIA       FAWCETT  2020-02-15 15:04:33+05:30
199       200      THORA        TEMPLE  2020-02-15 15:04:33+05:30

[200 rows x 4 columns]

In [11]:
# List of all your DataFrames
dfs = [actor, address, category, city, country, customer, film, film_actor, 
       film_category, inventory, language, payment, rental, staff, store]

for df in dfs:
    # Select only columns containing strings/objects to avoid converting numeric IDs 
    for col in df.select_dtypes(include=['object', 'string']).columns:
        try:
            # Attempt to convert to datetime in-place
            df[col] = pd.to_datetime(df[col])
        except Exception:
            # If it fails (e.g., because the column contains regular text), do nothing
            pass

print("Datetime conversion completed!")

C:\Users\dhanu\AppData\Local\Temp\ipykernel_13964\816000534.py:10: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[col] = pd.to_datetime(df[col])
C:\Users\dhanu\AppData\Local\Temp\ipykernel_13964\816000534.py:10: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[col] = pd.to_datetime(df[col])
C:\Users\dhanu\AppData\Local\Temp\ipykernel_13964\816000534.py:10: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[col] = pd.to_datetime(df[col])
C:\Users\dhanu\AppData\Local\Temp\ipykernel_13964\816000534.py:10: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[col] = pd.to_datetime(df[col])
C:\Users\dhanu\AppData\Local\Temp\ipykernel_13964\816000534.py:10: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[col] = pd.to_datetime(df[col])
C:\Users\dhanu\AppData\Local\Temp\ipykernel_13964\816000534.py:10: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[col] = pd.to_datetime(df[col])
C:\Users\dhanu\AppData\Local\Temp\ipykernel_13964\816000534.py:10: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[col] = pd.to_datetime(df[col])
C:\Users\dhanu\AppData\Local\Temp\ipykernel_13964\816000534.py:10: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[col] = pd.to_datetime(df[col])
C:\Users\dhanu\AppData\Local\Temp\ipykernel_13964\816000534.py:10: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[col] = pd.to_datetime(df[col])
C:\Users\dhanu\AppData\Local\Temp\ipykernel_13964\816000534.py:10: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[col] = pd.to_datetime(df[col])
C:\Users\dhanu\AppData\Local\Temp\ipykernel_13964\816000534.py:10: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[col] = pd.to_datetime(df[col])
C:\Users\dhanu\AppData\Local\Temp\ipykernel_13964\816000534.py:10: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[col] = pd.to_datetime(df[col])
C:\Users\dhanu\AppData\Local\Temp\ipykernel_13964\816000534.py:10: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[col] = pd.to_datetime(df[col])
C:\Users\dhanu\AppData\Local\Temp\ipykernel_13964\816000534.py:10: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[col] = pd.to_datetime(df[col])
C:\Users\dhanu\AppData\Local\Temp\ipykernel_13964\816000534.py:10: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[col] = pd.to_datetime(df[col])
C:\Users\dhanu\AppData\Local\Temp\ipykernel_13964\816000534.py:10: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[col] = pd.to_datetime(df[col])
C:\Users\dhanu\AppData\Local\Temp\ipykernel_13964\816000534.py:10: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[col] = pd.to_datetime(df[col])

Datetime conversion completed!

C:\Users\dhanu\AppData\Local\Temp\ipykernel_13964\816000534.py:10: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[col] = pd.to_datetime(df[col])
C:\Users\dhanu\AppData\Local\Temp\ipykernel_13964\816000534.py:10: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[col] = pd.to_datetime(df[col])
C:\Users\dhanu\AppData\Local\Temp\ipykernel_13964\816000534.py:10: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[col] = pd.to_datetime(df[col])
C:\Users\dhanu\AppData\Local\Temp\ipykernel_13964\816000534.py:10: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[col] = pd.to_datetime(df[col])
C:\Users\dhanu\AppData\Local\Temp\ipykernel_13964\816000534.py:10: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[col] = pd.to_datetime(df[col])

In [12]:
actor.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   actor_id     200 non-null    int64
 1   first_name   200 non-null    str
 2   last_name    200 non-null    str
 3   last_update  200 non-null    datetime64[us, UTC+05:30]
dtypes: datetime64[us, UTC+05:30](1), int64(1), str(2)
memory usage: 6.4 KB

In [17]:
revenue = payment['amount'].sum()
print(f"{revenue / 1000:.2f}K")

67.42K

In [18]:
# Total customers
len(customer)

599

In [19]:
len(payment)

16049

In [22]:
payment.shape[0]

16049

In [27]:


# 1. Load our CSV files into Pandas DataFrames (think of these as Excel sheets)
# Your files are inside the 'movie_dataset' folder, so we add that to the path!
rentals = pd.read_csv('movie_dataset/rental.csv')
customers = pd.read_csv('movie_dataset/customer.csv')
payments = pd.read_csv('movie_dataset/payment.csv')

# 2. Check the data types of our Rentals table
print("Before cleaning:")
print(rentals.dtypes)

# 3. Clean our dates! Let's find any column with 'date' in its name and convert it.
# We will use the rentals table as an example.
for col in rentals.columns:
    if 'date' in col.lower():
        # Convert to datetime, coercing errors to 'NaT' (Not a Time) so we don't crash
        rentals[col] = pd.to_datetime(rentals[col], errors='coerce')

print("\nAfter cleaning:")
print(rentals.dtypes)

Before cleaning:
rental_id       int64
rental_date       str
inventory_id    int64
customer_id     int64
return_date       str
staff_id        int64
last_update       str
dtype: object

After cleaning:
rental_id                           int64
rental_date     datetime64[us, UTC+05:30]
inventory_id                        int64
customer_id                         int64
return_date     datetime64[us, UTC+05:30]
staff_id                            int64
last_update     datetime64[us, UTC+05:30]
dtype: object

In [32]:
# 1. Total Revenue (adding up all the payments)
total_revenue = payments['amount'].sum()

# 2. Total Customers (counting unique people)
total_customers = customers['customer_id'].nunique()

# 3. Average Order Value (the average amount per payment)
average_order_value = payments['amount'].mean()

# 4. Let's print them out with some nice formatting!
print(f"💰 Total Revenue: ${total_revenue/1000:.2f}k")
print(f"👥 Total Customers: {total_customers:,}")
print(f"💳 Average Order Value: ${average_order_value:,.2f}")

💰 Total Revenue: $67.42k
👥 Total Customers: 599
💳 Average Order Value: $4.20

In [29]:
# 1. Merge (VLOOKUP) our payments and customers tables together.
# They both share the 'customer_id' column, so we use that as the bridge to connect them!
customer_spending = pd.merge(payments, customers, on='customer_id', how='left')

# 2. Group by (Pivot Table) to find our best customers!
top_customers = (
    customer_spending.groupby(['first_name', 'last_name'])['amount']
    .sum()
    .reset_index()
    .sort_values(by='amount', ascending=False)
)

print("🏆 Top 5 Customers by Revenue:")
print(top_customers.head(5))

🏆 Top 5 Customers by Revenue:
    first_name last_name  amount
318       KARL      SEAL  221.55
175    ELEANOR      HUNT  216.54
105      CLARA      SHAW  195.58
389     MARION    SNYDER  194.61
474     RHONDA   KENNEDY  194.61